# Generated by Django 2.2.1 on 2019-05-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('automatically_extensible', models.BooleanField(default=True)),
                ('use_synonyms', models.BooleanField(default=True)),
                ('matching_strictness', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='EntityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='querybot.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('entity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='querybot.EntityRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('name', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('category', models.CharField(default='General', max_length=100)),
                ('related_entities', models.ManyToManyField(blank=True, null=True, related_name='intents', to='querybot.Entity')),
            ],
        ),
    ]
