# Generated by Django 2.2.1 on 2019-05-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querybot', '0003_entity_entity_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utterance',
        ),
    ]
