# Generated by Django 2.2.1 on 2019-05-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querybot', '0006_auto_20190508_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityslot',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='querybot.Entity'),
        ),
    ]
