# Generated by Django 2.2.1 on 2019-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querybot', '0007_auto_20190509_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityslot',
            name='example_value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
